In [14]:
import numpy as np

np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

In [15]:
def grad(x):
    return np.dot(Q, x) - b

def grad_equals_zero(g):
    return not np.any(np.around(g, decimals=4))

In [16]:
def conjugate_direction(f, d, x0):
    
    (Q, b) = f
    
    x = [x0]
    print("x[{0}]: \n".format(0), x[0])
    
    g = [grad(x[0])]
    print("g[{0}]: \n".format(0), g[0])
    
    alpha = []
    
    k = 0
    while not grad_equals_zero(g[k]):
        print("\n\nIteration ", k+1)
        
        alpha.append(-np.dot(g[k].T, d[k]).item()/np.dot(np.dot(d[k].T, Q), d[k]).item())
        print("alpha[{0}]: ".format(k), alpha[k])
        
        x.append(x[k] + alpha[k]*d[k])
        print("x[{0}]: \n".format(k+1), x[k+1])
        
        g.append(grad(x[k+1]))
        print("g[{0}]: \n".format(k+1), g[k+1])
        
        k += 1
    
    print("\n")
    
    return x[k]
    

In [17]:
#Eg. 10.2

#The quadratic function
Q = np.array([[4, 2], [2, 2]])
b = np.array([[-1, 1]]).T
f = (Q, b)

#The conjugate directions
d0 = np.array([[1, 0]]).T
d1 = np.array([[-3/8, 3/4]]).T
d = [d0, d1]

#The initial point
x0 = np.array([[0, 0]]).T

print("Minimizer, x* =\n", conjugate_direction(f, d, x0))

x[0]: 
 [[0]
 [0]]
g[0]: 
 [[ 1]
 [-1]]


Iteration  1
alpha[0]:  -0.25
x[1]: 
 [[-0.25]
 [ 0.  ]]
g[1]: 
 [[ 0. ]
 [-1.5]]


Iteration  2
alpha[1]:  2.0
x[2]: 
 [[-1. ]
 [ 1.5]]
g[2]: 
 [[0.]
 [0.]]


Minimizer, x* =
 [[-1. ]
 [ 1.5]]


In [18]:
#Eg. 10.3
Q = np.array([[3, 0, 1], [0, 4, 2], [1, 2, 3]])
b = np.array([[3, 0, 1]]).T
f = (Q, b)

d0 = np.array([[3, 0, 1]]).T
d1 = np.array([[0.463, -0.5556, -0.5864]]).T
d2 = np.array([[0.0795, 0.1476, -0.1817]]).T
d = [d0, d1, d2]

x0 = np.array([[0, 0, 0]]).T

print("\nMinimizer, x* = \n", conjugate_direction(f, d, x0))

#Error comes for this one because if you see in the third iteration g[k] is almost zero
#(In the conjugate_gradient algorithm it does go to zero).
#Note that this happens because I've rounded up the conjugate directions
#(which were actually obtained using the conjugate_gradient algorithm)

#Thus, since we are dealing with rounded-off directions we don't get the desired answer.

#BEWARE!! Of such numerical issues...

x[0]: 
 [[0]
 [0]
 [0]]
g[0]: 
 [[-3]
 [ 0]
 [-1]]


Iteration  1
alpha[0]:  0.2777777777777778
x[1]: 
 [[0.8333]
 [0.    ]
 [0.2778]]
g[1]: 
 [[-0.2222]
 [ 0.5556]
 [ 0.6667]]


Iteration  2
alpha[1]:  0.21868111180882938
x[2]: 
 [[ 0.9346]
 [-0.1215]
 [ 0.1495]]
g[2]: 
 [[-0.0467]
 [-0.1869]
 [ 0.1402]]


Iteration  3
alpha[2]:  0.8230812283392239
x[3]: 
 [[ 1.]
 [-0.]
 [-0.]]
g[3]: 
 [[ 0.    ]
 [-0.0001]
 [-0.    ]]


Iteration  4


IndexError: list index out of range