In [5]:
import numpy as np

np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

In [6]:
def grad(x):
    return np.dot(Q, x) - b

def grad_equals_zero(g):
    return not np.any(np.around(g, decimals=4))

In [7]:
#The Conjugate Gradient algorithm...

def conjugate_gradient(f, initial_pt):
    
    (Q, b) = f

    x = []
    g = []
    d = []
    alpha = []
    beta = []
        
    k = 0
    print("\n\nIteration ", k)
    
    x.append(initial_pt)
    print("x[{0}]: \n".format(0), x[0])
    
    g.append(grad(x[0]))
    print("g[{0}]: \n".format(0), g[0])
    
    if grad_equals_zero(g[0]):    
        return x[0] 
    else:
        d.append(-g[0])
        print("d[{0}]: \n".format(0), d[0])

    
    
    while(True):
        print("\n\nIteration ", k+1)
        
        alpha.append(-np.dot(g[k].T, d[k]).item()/(np.dot(np.dot(d[k].T, Q), d[k]).item()))

        print("alpha[{0}]: ".format(k), alpha[k])
        
        x.append(x[k] + alpha[k]*d[k])
        print("x[{0}]: \n".format(k+1), x[k+1])
        
        g.append(grad(x[k+1]))
        print("g[{0}]: \n".format(k+1), g[k+1])
        
        if grad_equals_zero(g[k+1]):
            return x[k+1]
        
        beta.append(np.dot(np.dot(g[k+1].T, Q), d[k]).item()/(np.dot(np.dot(d[k].T, Q), d[k]).item()))
        print("beta[{0}]: ".format(k), beta[k])
        
        d.append(-g[k+1] + beta[k]*d[k])
        print("d[{0}]: \n".format(k+1), d[k+1])
        
        k += 1

In [11]:
#Ex. 10.10
Q = np.array([[5, 2], [2, 1]])
b = np.array([[3, 1]]).T
f = (Q, b)
x0 = np.array([[0, 0]]).T

print("\nMinimizer, x* = \n", conjugate_gradient(f, x0))



Iteration  0
x[0]: 
 [[0]
 [0]]
g[0]: 
 [[-3]
 [-1]]
d[0]: 
 [[3]
 [1]]


Iteration  1
alpha[0]:  0.1724137931034483
x[1]: 
 [[0.5172]
 [0.1724]]
g[1]: 
 [[-0.069 ]
 [ 0.2069]]
beta[0]:  0.004756242568371073
d[1]: 
 [[ 0.0832]
 [-0.2021]]


Iteration  2
alpha[1]:  5.799999999999999
x[2]: 
 [[ 1.]
 [-1.]]
g[2]: 
 [[0.]
 [0.]]

Minimizer, x* = 
 [[ 1.]
 [-1.]]


In [12]:
#Eg. 10.3
Q = np.array([[3, 0, 1], [0, 4, 2], [1, 2, 3]])
b = np.array([[3, 0, 1]]).T
f = (Q, b)
x0 = np.array([[0, 0, 0]]).T

print("\nMinimizer, x* = \n", conjugate_gradient(f, x0))



Iteration  0
x[0]: 
 [[0]
 [0]
 [0]]
g[0]: 
 [[-3]
 [ 0]
 [-1]]
d[0]: 
 [[3]
 [0]
 [1]]


Iteration  1
alpha[0]:  0.2777777777777778
x[1]: 
 [[0.8333]
 [0.    ]
 [0.2778]]
g[1]: 
 [[-0.2222]
 [ 0.5556]
 [ 0.6667]]
beta[0]:  0.0802469135802469
d[1]: 
 [[ 0.463 ]
 [-0.5556]
 [-0.5864]]


Iteration  2
alpha[1]:  0.21869158878504677
x[2]: 
 [[ 0.9346]
 [-0.1215]
 [ 0.1495]]
g[2]: 
 [[-0.0467]
 [-0.1869]
 [ 0.1402]]
beta[1]:  0.0707485369901304
d[2]: 
 [[ 0.0795]
 [ 0.1476]
 [-0.1817]]


Iteration  3
alpha[2]:  0.8230769230769229
x[3]: 
 [[ 1.]
 [-0.]
 [-0.]]
g[3]: 
 [[-0.]
 [-0.]
 [-0.]]

Minimizer, x* = 
 [[ 1.]
 [-0.]
 [-0.]]


In [4]:
Q = np.array([[5, -3], [-3, 2]])
b = np.array([[0, 1]]).T
f = (Q, b)

x0 = np.array([[0, 0]]).T

print("\nMinimizer, x* = \n", conjugate_gradient(f, x0))



Iteration  0
x[0]: 
 [[0]
 [0]]
g[0]: 
 [[ 0]
 [-1]]
d[0]: 
 [[0]
 [1]]


Iteration  1
alpha[0]:  0.5
x[1]: 
 [[0. ]
 [0.5]]
g[1]: 
 [[-1.5]
 [ 0. ]]
beta[0]:  2.25
d[1]: 
 [[1.5 ]
 [2.25]]


Iteration  2
alpha[1]:  2.0
x[2]: 
 [[3.]
 [5.]]
g[2]: 
 [[0.]
 [0.]]

Minimizer, x* = 
 [[3.]
 [5.]]


In [8]:
#Ex. 10.10
Q = np.array([[3, 1], [1, 2]])
b = np.array([[0, 0]]).T
f = (Q, b)
x0 = np.array([[0, 0]]).T

print("\nMinimizer, x* = \n", conjugate_gradient(f, x0))



Iteration  0
x[0]: 
 [[0]
 [0]]
g[0]: 
 [[0]
 [0]]

Minimizer, x* = 
 [[0]
 [0]]


In [ ]:
**