In [2]:
import numpy as np
import math

np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

In [3]:
def grad(x):
    return np.dot(Q, x) - b

def grad_equals_zero(g):
    return not np.any(np.around(g, decimals=4))

In [4]:
def steepest_descent(f, x0):
    
    (Q, b) = f
    
    x = [x0]
    print("x[{0}]:\n".format(0), x[0])
    
    g = [grad(x[0])]
    print("g[{0}]:\n".format(0), g[0])
    
    alpha = []
    
    print("\n")
    
    i = 0
    while not grad_equals_zero(g[i]):
        
        alpha.append(np.dot(g[i].T, g[i]).item()/np.dot(np.dot(g[i].T, Q), g[i]).item())
        print("alpha[{0}]: ".format(i), alpha[i])
        
        x.append(x[i] - alpha[i]*g[i])
        print("x[{0}]:\n".format(i+1), x[i+1])
        
        i += 1
        
        g.append(grad(x[i]))
        print("g[{0}]:\n".format(i), g[i])
        
        print("\n")
    
    return x[-1]

In [12]:
#Ex. 10.10
Q = np.array([[5, 2], [2, 1]])
b = np.array([[3, 1]]).T
f = (Q, b)

x0 = np.array([[0, 0]]).T

mini = steepest_descent(f, x0)
print("Minimizer =")
print(mini)

x[0]:
 [[0]
 [0]]
g[0]:
 [[-3]
 [-1]]


alpha[0]:  0.1724137931034483
x[1]:
 [[0.5172]
 [0.1724]]
g[1]:
 [[-0.069 ]
 [ 0.2069]]


alpha[1]:  4.999999999999975
x[2]:
 [[ 0.8621]
 [-0.8621]]
g[2]:
 [[-0.4138]
 [-0.1379]]


alpha[2]:  0.1724137931034483
x[3]:
 [[ 0.9334]
 [-0.8383]]
g[3]:
 [[-0.0095]
 [ 0.0285]]


alpha[3]:  5.0
x[4]:
 [[ 0.981]
 [-0.981]]
g[4]:
 [[-0.0571]
 [-0.019 ]]


alpha[4]:  0.17241379310344823
x[5]:
 [[ 0.9908]
 [-0.9777]]
g[5]:
 [[-0.0013]
 [ 0.0039]]


alpha[5]:  5.00000000000203
x[6]:
 [[ 0.9974]
 [-0.9974]]
g[6]:
 [[-0.0079]
 [-0.0026]]


alpha[6]:  0.1724137931034455
x[7]:
 [[ 0.9987]
 [-0.9969]]
g[7]:
 [[-0.0002]
 [ 0.0005]]


alpha[7]:  4.9999999999779146
x[8]:
 [[ 0.9996]
 [-0.9996]]
g[8]:
 [[-0.0011]
 [-0.0004]]


alpha[8]:  0.17241379310347452
x[9]:
 [[ 0.9998]
 [-0.9996]]
g[9]:
 [[-0.    ]
 [ 0.0001]]


alpha[9]:  4.999999999928838
x[10]:
 [[ 1.]
 [-1.]]
g[10]:
 [[-0.0001]
 [-0.    ]]


alpha[10]:  0.17241379310351707
x[11]:
 [[ 1.    ]
 [-0.9999]]
g[11

In [13]:
#Eg. 10.3
Q = np.array([[3, 0, 1], [0, 4, 2], [1, 2, 3]])
b = np.array([[3, 0, 1]]).T
f = (Q, b)
x0 = np.array([[0, 0, 0]]).T

print("\nMinimizer, x* = \n", steepest_descent(f, x0))

x[0]:
 [[0]
 [0]
 [0]]
g[0]:
 [[-3]
 [ 0]
 [-1]]


alpha[0]:  0.2777777777777778
x[1]:
 [[0.8333]
 [0.    ]
 [0.2778]]
g[1]:
 [[-0.2222]
 [ 0.5556]
 [ 0.6667]]


alpha[1]:  0.20569620253164558
x[2]:
 [[ 0.879 ]
 [-0.1143]
 [ 0.1406]]
g[2]:
 [[-0.2222]
 [-0.1758]
 [ 0.0724]]


alpha[2]:  0.4184984720505011
x[3]:
 [[ 0.972 ]
 [-0.0407]
 [ 0.1103]]
g[3]:
 [[0.0265]
 [0.0579]
 [0.2216]]


alpha[3]:  0.23538293791474899
x[4]:
 [[ 0.9658]
 [-0.0543]
 [ 0.0582]]
g[4]:
 [[-0.0444]
 [-0.101 ]
 [ 0.0317]]


alpha[4]:  0.3861617058727028
x[5]:
 [[ 0.983 ]
 [-0.0153]
 [ 0.0459]]
g[5]:
 [[-0.0052]
 [ 0.0305]
 [ 0.0901]]


alpha[5]:  0.23741268530360504
x[6]:
 [[ 0.9842]
 [-0.0226]
 [ 0.0245]]
g[6]:
 [[-0.0229]
 [-0.0412]
 [ 0.0127]]


alpha[6]:  0.38542041600120397
x[7]:
 [[ 0.993 ]
 [-0.0067]
 [ 0.0197]]
g[7]:
 [[-0.0013]
 [ 0.0126]
 [ 0.0386]]


alpha[7]:  0.23744970843507102
x[8]:
 [[ 0.9933]
 [-0.0097]
 [ 0.0105]]
g[8]:
 [[-0.0095]
 [-0.0177]
 [ 0.0054]]


alpha[8]:  0.3854076544821878
x[9]:
 [

In [14]:
#Ex. 7.12
Q = np.array([[2, 1], [1, 2]])
b = np.array([[0, 0]]).T
f = (Q, b)

x0 = np.array([[0.8, -0.25]]).T

print("\nMinimizer, x* = \n", steepest_descent(f, x0))

x[0]:
 [[ 0.8 ]
 [-0.25]]
g[0]:
 [[1.35]
 [0.3 ]]


alpha[0]:  0.41262135922330095
x[1]:
 [[ 0.243 ]
 [-0.3738]]
g[1]:
 [[ 0.1121]
 [-0.5046]]


alpha[1]:  0.6343283582089552
x[2]:
 [[ 0.1718]
 [-0.0537]]
g[2]:
 [[0.29  ]
 [0.0644]]


alpha[2]:  0.41262135922330095
x[3]:
 [[ 0.0522]
 [-0.0803]]
g[3]:
 [[ 0.0241]
 [-0.1084]]


alpha[3]:  0.6343283582089553
x[4]:
 [[ 0.0369]
 [-0.0115]]
g[4]:
 [[0.0623]
 [0.0138]]


alpha[4]:  0.41262135922330095
x[5]:
 [[ 0.0112]
 [-0.0172]]
g[5]:
 [[ 0.0052]
 [-0.0233]]


alpha[5]:  0.6343283582089553
x[6]:
 [[ 0.0079]
 [-0.0025]]
g[6]:
 [[0.0134]
 [0.003 ]]


alpha[6]:  0.4126213592233009
x[7]:
 [[ 0.0024]
 [-0.0037]]
g[7]:
 [[ 0.0011]
 [-0.005 ]]


alpha[7]:  0.6343283582089556
x[8]:
 [[ 0.0017]
 [-0.0005]]
g[8]:
 [[0.0029]
 [0.0006]]


alpha[8]:  0.4126213592233008
x[9]:
 [[ 0.0005]
 [-0.0008]]
g[9]:
 [[ 0.0002]
 [-0.0011]]


alpha[9]:  0.6343283582089556
x[10]:
 [[ 0.0004]
 [-0.0001]]
g[10]:
 [[0.0006]
 [0.0001]]


alpha[10]:  0.4126213592233009
x[

In [7]:
#Ex. 8.1
Q = np.array([[1, 0], [0, 2]])
b = np.array([[1, 1/2]]).T
f = (Q, b)

x0 = np.array([[0, 0]]).T

print("\nMinimizer, x* = \n", steepest_descent(f, x0))

x[0]:
 [[0]
 [0]]
g[0]:
 [[-1. ]
 [-0.5]]


alpha[0]:  0.8333333333333334
x[1]:
 [[0.8333]
 [0.4167]]
g[1]:
 [[-0.1667]
 [ 0.3333]]


alpha[1]:  0.5555555555555555
x[2]:
 [[0.9259]
 [0.2315]]
g[2]:
 [[-0.0741]
 [-0.037 ]]


alpha[2]:  0.8333333333333337
x[3]:
 [[0.9877]
 [0.2623]]
g[3]:
 [[-0.0123]
 [ 0.0247]]


alpha[3]:  0.5555555555555551
x[4]:
 [[0.9945]
 [0.2486]]
g[4]:
 [[-0.0055]
 [-0.0027]]


alpha[4]:  0.8333333333333335
x[5]:
 [[0.9991]
 [0.2509]]
g[5]:
 [[-0.0009]
 [ 0.0018]]


alpha[5]:  0.5555555555555496
x[6]:
 [[0.9996]
 [0.2499]]
g[6]:
 [[-0.0004]
 [-0.0002]]


alpha[6]:  0.8333333333333335
x[7]:
 [[0.9999]
 [0.2501]]
g[7]:
 [[-0.0001]
 [ 0.0001]]


alpha[7]:  0.5555555555555556
x[8]:
 [[1.  ]
 [0.25]]
g[8]:
 [[-0.]
 [-0.]]



Minimizer, x* = 
 [[1.  ]
 [0.25]]
